"""This script is run by Mantra to execute custom Python filtering of IFDs
before, during and after render time.

For more information, please see:
    http://www.sidefx.com/docs/houdini/rendering/python

"""

# =============================================================================
# IMPORTS
# =============================================================================

# Standard Library Imports
import logging

# Houdini Toolbox Imports
import ht.logging

ht.logging.init_config()

from ht.pyfilter.manager import PyFilterManager
from ht.pyfilter.property import get_property

_logger = logging.getLogger("ht-pyfilter")


# =============================================================================
# GLOBALS
# =============================================================================

_PYFILTER_MANAGER = None


# =============================================================================
# FUNCTIONS
# =============================================================================

def filterCamera():
    """Modify image related properties.

    Called just before the global properties are locked off for the render.
    This is usually prior to the declaration of any objects in the IFD.  If you
    change global properties after this, they probably will have no effect.

    Since mantra calls this function before any lights or instances are
    declared, you can set default light or instance properties here.  Mantra
    will apply any Instance/Light properties you set here to any objects which
    don't declare the property explicitly.

    """
    _logger.debug("filterCamera")

    _PYFILTER_MANAGER.run_operations_for_stage("filterCamera")


def filterCameraSegment():
    """Modify properties for a camera motion segment.

    Called just prior to the ray_end statement locking the settings for a
    camera motion segment.

    """
    _logger.debug("filterCameraSegment")

    _PYFILTER_MANAGER.run_operations_for_stage("filterCameraSegment")


def filterEndRender():
    """Perform actions just after the image has been rendered."""
    _logger.debug("filterEndRender")

    _PYFILTER_MANAGER.run_operations_for_stage("filterEndRender")


def filterError(level, message, prefix):
    """Process information, warning or error messages printed by Mantra.

    This function allows you to disable the printing of messages.

    """
    result = _PYFILTER_MANAGER.run_operations_for_stage("filterError", level, message, prefix)

    return result


def filterFog():
    """Modify fog related properties.

    Called just prior to the ray_end statement which locks off the settings for
    a fog object. The function can query fog: settings and possibly alter them.

    """
    _logger.debug("filterFog (%s)", get_property("object:name"))

    _PYFILTER_MANAGER.run_operations_for_stage("filterFog")


def filterGeometry():
    """Modify geometry related properties.

    Called just prior to the ray_end statement which locks off a geometry
    object. This allows the program to query geometry: settings and possibly
    alter them.

    """
    _logger.debug("filterGeometry")

    _PYFILTER_MANAGER.run_operations_for_stage("filterGeometry")


def filterInstance():
    """Modify object related properties.

    Called just prior to the ray_end statement which locks off the settings for
    an instance object.  The function can query object: settings and possibly
    alter them.

    """
    _logger.debug("filterInstance (%s)", get_property("object:name"))
    _PYFILTER_MANAGER.run_operations_for_stage("filterInstance")


def filterLight():
    """Modify light related properties.

    Called just prior to the ray_end statement which locks off the settings for
    a light object.  The function can query light: settings and possibly alter
    them.

    """
    _logger.debug("filterLight (%s)", get_property("object:name"))

    _PYFILTER_MANAGER.run_operations_for_stage("filterLight")


def filterMaterial():
    """Modify material related properties.

    Mantra has material blocks which can be applied on a per-primitive basis.
    This function is called before a material is locked off. The function can
    add or change properties on the material.

    """
    _logger.debug("filterMaterial")

    _PYFILTER_MANAGER.run_operations_for_stage("filterMaterial")


def filterOutputAssets(assets):  # pylint: disable=unused-argument
    """Filter assets generated by Mantra.

    Called after the render completes, and is passed a list of assets generated
    during the render.

    """
    _logger.debug("filterOutputAssets")

    _PYFILTER_MANAGER.run_operations_for_stage("filterOutputAssets")


def filterPlane():
    """Change query and modify image plane properties."""
    variable = get_property("plane:variable")
    channel = get_property("plane:channel")

    if variable == channel or channel == "":
        _logger.debug("filterPlane (%s)", variable)
    else:
        _logger.debug("filterPlane (%s -> %s)", variable, channel)

    _PYFILTER_MANAGER.run_operations_for_stage("filterPlane")


def filterQuit():
    """Perform actions just before Mantra quits."""
    _logger.debug("filterQuit")

    _PYFILTER_MANAGER.run_operations_for_stage("filterQuit")


def filterRender():
    """Query render related properties.

    Called just before the ray_raytrace command.  It's not possible to change
    any properties at this time in the IFD processing.  However, for
    statistics or validation, it might be useful to have this method available.

    """
    _logger.debug("filterRender")

    _PYFILTER_MANAGER.run_operations_for_stage("filterRender")


def main():
    """Build the manager."""
    global _PYFILTER_MANAGER

    _PYFILTER_MANAGER = PyFilterManager()


# =============================================================================

if __name__ == "__main__":
    main()
