
DSONAME = SOP_PrimCentroid.so
HELP = primcentroid.txt
HELPCONTEXT = sop
ICONS = SOP_primcentroid.svg
SHELFTOOLS = sop_primcentroid.shelf
SOURCES = SOP_PrimCentroid.C

include $(TOOLBOXDIR)/Makefile.gnu

