
DSONAME = SOP_PointsFromVoxels.so
HELP = pointsfromvoxels.txt
HELPCONTEXT = sop
ICONS = SOP_pointsfromvoxels.svg
SHELFTOOLS = sop_pointsfromvoxels.shelf
SOURCES = SOP_PointsFromVoxels.C

include $(TOOLBOXDIR)/Makefile.gnu

