
DSONAME = SOP_IdAttribCopy.so
HELP = idattribcopy.txt
HELPCONTEXT = sop
ICONS = SOP_idattribcopy.svg
SHELFTOOLS = sop_idattribcopy.shelf
SOURCES = SOP_IdAttribCopy.C

include $(TOOLBOXDIR)/plugins/Makefile.gnu

