
DSONAME = SOP_PrimGroupCentroid.so
HELP = primgroupcentroid.txt
HELPCONTEXT = sop
ICONS = SOP_primgroupcentroid.svg
SHELFTOOLS = sop_primgroupcentroid.shelf
SOURCES = SOP_PrimGroupCentroid.C

include $(TOOLBOXDIR)/Makefile.gnu

